"""
CLI entry point for ``agent-commit``.

Commits files using the agent's git author identity.  The commit
message is generated by sending the staged diff to the LLM backend.

Usage
-----
    agent-commit --tracked              Commit tracked modified files
    agent-commit --all                  Commit all changed files (including untracked)
    agent-commit file1.py file2.py      Commit specific files
    agent-commit -o --all               Use online model for commit message
"""

import argparse
import os
import platform
import re
import sys

from ..backends import create_backend
from ..git_utils import (
    is_git_repo,
    get_all_changed_files,
    get_staged_files,
    get_tracked_modified_files,
    git_add_and_commit,
    _run_git,
)


_BACKTICK = "`" * 5
_CODE_FENCE = "`" * 3


def _extract_backtick_block(text: str) -> str | None:
    """Extract the first 5-backtick-wrapped block from *text*."""
    match = re.search(rf"{_BACKTICK}([\s\S]*?){_BACKTICK}", text)
    if match:
        return match.group(1).strip()
    return None


_AGENTS_CONFIG_DIR = os.path.join(os.path.expanduser("~"), ".agents")


def _read_configuration(configuration_name: str) -> dict:
    """Read agent configuration from a YAML file."""
    import yaml
    user_config = os.path.join(_AGENTS_CONFIG_DIR, configuration_name)
    if os.path.isfile(user_config):
        with open(user_config, "r") as f:
            return yaml.safe_load(f)
    script_dir = os.path.dirname(os.path.realpath(os.path.abspath(__file__)))
    config_path = os.path.join(script_dir, "..", configuration_name)
    with open(config_path, "r") as f:
        return yaml.safe_load(f)


def _format_host_for_url(host: str) -> str:
    """Wrap an IPv6 address in brackets for use in URLs."""
    if host.startswith("[") and host.endswith("]"):
        return host
    if ":" in host:
        return f"[{host}]"
    return host


def _get_agent_author() -> tuple[str, str]:
    """Return (author_name, author_email) matching the agent's identity."""
    model = os.environ.get("LOCAL_MODEL", os.environ.get("AGENT_MODEL", "agent"))
    hostname = platform.node()
    return model, f"agent@{hostname}"


def _auto_message(files: list[str]) -> str:
    """Generate a simple commit message from file basenames."""
    names = [os.path.basename(f) for f in files]
    if len(names) == 1:
        return f"update {names[0]}"
    return f"update {', '.join(names)}"


COMMIT_SYSTEM_PROMPT = (
    "You are a git commit message generator. You receive a unified diff "
    "and must produce a single, concise commit message on one line. "
    "Wrap the message in five backticks."
)


def _generate_commit_message(
    diff: str,
    files: list[str],
    *,
    online: bool = False,
    agent_config: str = "basic_agent.yaml",
) -> str:
    """Send the diff to the LLM and extract a commit message.

    Falls back to ``_auto_message()`` if the LLM is unavailable or
    produces no extractable message.
    """
    config = _read_configuration(agent_config)

    if online:
        provider = os.environ.get(
            "AGENT_MODEL_PROVIDER",
            config.get("provider", "anthropic"),
        )
        model = os.environ.get("AGENT_MODEL")
        base_url = config.get("base_url", None)
        if not model:
            provider_defaults = {
                "anthropic": "claude-opus-4-6",
                "openai": "gpt-5.3-codex",
                "gemini": "gemini-3.1-pro-preview",
            }
            model = provider_defaults.get(provider, "claude-opus-4-6")
    else:
        model = os.environ.get("LOCAL_MODEL")
        if not model:
            return _auto_message(files)
        local_host = os.environ.get("LOCAL_LLM_HOST", "localhost")
        local_port = os.environ.get("LOCAL_LLM_PORT", "8000")
        provider = "anthropic"
        base_url = f"http://{_format_host_for_url(local_host)}:{local_port}"

    try:
        client = create_backend(
            provider,
            model=model,
            base_url=base_url,
        )
    except Exception:
        return _auto_message(files)

    # Truncate diff to avoid overwhelming the context window
    max_diff = 30_000
    if len(diff) > max_diff:
        diff = (
            diff[:max_diff]
            + f"\n\n... [diff truncated, {len(diff) - max_diff:,} more chars] ..."
        )

    file_list = ", ".join(os.path.basename(f) for f in files)
    fence = _CODE_FENCE
    user_message = f"Files changed: {file_list}\n\n{fence}\n{diff}\n{fence}"

    context = [
        {"role": "user", "content": [{"type": "text", "text": user_message}]}
    ]

    try:
        response = client.generate_response(COMMIT_SYSTEM_PROMPT, context)
    except Exception:
        return _auto_message(files)

    # Extract backtick-wrapped message
    message = _extract_backtick_block(response)
    if message:
        return message.split("\n")[0].strip()

    # Fallback: use the first line of the raw response
    first_line = response.strip().split("\n")[0].strip()
    if first_line:
        return first_line

    return _auto_message(files)


def main():
    """Parse arguments and perform the commit."""
    parser = argparse.ArgumentParser(
        prog="agent-commit",
        description="Commit files using the agent's git author identity.",
    )

    mode = parser.add_mutually_exclusive_group()
    mode.add_argument(
        "--tracked",
        action="store_true",
        help="Commit all tracked files with changes (modified, deleted, renamed).",
    )
    mode.add_argument(
        "--all",
        action="store_true",
        help="Commit all changed files including untracked ones.",
    )
    parser.add_argument(
        "-o", "--online",
        action="store_true",
        help="Use the online model provider for the commit message.",
    )
    parser.add_argument(
        "files",
        nargs="*",
        help="Specific files to commit (used when --tracked and --all are omitted).",
    )

    args = parser.parse_args()

    if not is_git_repo("."):
        print("Error: not a git repository.", file=sys.stderr)
        sys.exit(1)

    author_name, author_email = _get_agent_author()

    if args.tracked:
        files = sorted(
            set(get_tracked_modified_files(".")) | set(get_staged_files("."))
        )
        if not files:
            print("No tracked files with changes to commit.")
            sys.exit(0)
    elif args.all:
        files = get_all_changed_files(".")
        if not files:
            print("No files to commit.")
            sys.exit(0)
    else:
        if not args.files:
            parser.error("Provide --tracked, --all, or specific file paths.")
        files = args.files

    # Stage files first so we can get the diff
    _, stderr, rc = _run_git("add", *files, cwd=".")
    if rc != 0:
        print(f"git add failed: {stderr}", file=sys.stderr)
        sys.exit(1)

    # Get the staged diff for the LLM
    diff, _, _ = _run_git("diff", "--cached", cwd=".")

    # Generate commit message from the diff
    message = _generate_commit_message(diff, files, online=args.online)

    # Commit (files are already staged)
    ok, err = git_add_and_commit(
        message,
        author_name=author_name,
        author_email=author_email,
        files=files,
    )

    if ok:
        print(f"Committed {len(files)} file(s) as {author_name} <{author_email}>:")
        for f in files:
            print(f"  {f}")
        print(f'  "{message}"')
    else:
        print(f"Commit failed: {err}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
